### ISSUE TITLE
Automake Error (RHEL 7.5)

### ISSUE THREAD

**Issue by harkabeeparolus** [baszoetekouw/pinfo#14]
I get the following error when running `automake --add-missing --copy --force-missing` (started automatically from `autoreconf -fiv`:

`doc/Makefile.am:4: error: option 'info-in-builddir' not recognized`

* Red Hat Enterprise Linux Workstation release 7.5 (Maipo)
  * autoconf 2.69
  * automake 1.13.4
  * libtool 2.4.2
  * gettext-devel 0.19.8.1

**Comment by harkabeeparolus** [comment]
Never mind. This is a new option in automake 1.14, so I guess RHEL 7.5 is just too old. 🙃

Maybe make a note of this in the build instructions?

**Comment by xaizek** [comment]
@baszoetekouw I think this can be closed now that #15 is merged.

**Comment by harkabeeparolus** [comment]
Indeed. Thanks! 😄
