### ISSUE TITLE
pinfo occasionally fails to find some nodes.

### ISSUE THREAD

**Issue by gnarendran** [baszoetekouw/pinfo#6]
1.When used on ls in coreutils, strace shows that pinfo goes looking for invalid files such as coreutils.gz instead of coreutils.info.gz, and fails to display the info node. This doesn't always happen though, and depends on whether pinfo looked up another .info file prior to this.

2. When the node link spans multiple lines and contain repeating spaces due to the margin, following the link fails. This happens for example for this link: ls->What information is listed->Formatting the file names

3. When a man page is looked up without specifiying its section, and if it contains a link to a man page with the same name but in a different section, the link is ignored. This happens for example sleep(1) which has a link to sleep(3).

The attached patch addresses these issues.
[pinfo_patch.txt](https://github.com/baszoetekouw/pinfo/files/2096909/pinfo_patch.txt)

**Comment by baszoetekouw** [comment]
Thanks for the patches!  I've just merged them.

However in the furture, could you please open separate pull requests/issues for unrelated issues?  That would make things easier to track for me.

**Comment by gnarendran** [comment]
OK, thanks for merging the patch. Regards.
